# Generated by Django 4.0.5 on 2022-06-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'players',
                'verbose_name_plural': 'Players',
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('players', models.ManyToManyField(to='sports.players')),
            ],
            options={
                'verbose_name': 'sports',
                'verbose_name_plural': 'Sports',
                'db_table': 'sports',
            },
        ),
    ]
