# Generated by Django 4.0.5 on 2022-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='email',
        ),
        migrations.AddField(
            model_name='sports',
            name='name',
            field=models.CharField(default='Baseball', max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
